#!/usr/bin/env python3
"""Ledger consistency validator for virtual-trader.

Checks INV-1 through INV-7. Returns exit 0 if all pass, 1 if any fail.
Designed to be imported by tests (validate()) or run standalone (main()).

Usage:
    python3 scripts/validate_ledger_consistency.py [--strict]
    --strict: also check INV-7 (live accounts), requires accounts/*.json
"""
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

VTRADER_HOME = os.environ.get("VTRADER_HOME", os.path.expanduser("~/.hermes/virtual-trader"))

TOLERANCE_PCT = 0.03  # ±0.03% tolerance for float comparison


def _load_json(path: str) -> Optional[dict]:
    try:
        with open(path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None


def _list_dates_in_dir(directory: str, pattern: str = "*.json") -> set:
    """Extract YYYY-MM-DD dates from filenames in a directory."""
    dates = set()
    p = Path(directory)
    if not p.exists():
        return dates
    for f in p.glob(pattern):
        m = re.search(r"(\d{4}-\d{2}-\d{2})", f.name)
        if m:
            dates.add(m.group(1))
    return dates


def _extract_report_daily_return(filepath: str) -> Tuple[Optional[float], Optional[float]]:
    """Extract main_pct and lab_pct from a daily report markdown file."""
    try:
        with open(filepath) as f:
            text = f.read()
    except FileNotFoundError:
        return None, None

    # Match "总资产：XXX（+/-X.XX%）| 持仓"
    main_m = re.search(r"主账户.*?总资产：[\d,.]+（([+-]?[\d.]+)%）", text, re.DOTALL)
    lab_m = re.search(r"实验账户.*?总资产：[\d,.]+（([+-]?[\d.]+)%）", text, re.DOTALL)
    main_pct = float(main_m.group(1)) if main_m else None
    lab_pct = float(lab_m.group(1)) if lab_m else None
    return main_pct, lab_pct


class LedgerValidator:
    def __init__(self, root: str = None, strict: bool = False):
        self.root = root or VTRADER_HOME
        self.strict = strict
        self.results: List[dict] = []

    def _pass(self, inv: str, msg: str):
        self.results.append({"inv": inv, "status": "PASS", "msg": msg})

    def _fail(self, inv: str, msg: str):
        self.results.append({"inv": inv, "status": "FAIL", "msg": msg})

    def _warn(self, inv: str, msg: str):
        self.results.append({"inv": inv, "status": "WARN", "msg": msg})

    def _skip(self, inv: str, msg: str):
        self.results.append({"inv": inv, "status": "SKIP", "msg": msg})

    # ── INV-1: Every trading day (has trade file) must have perf entry ──

    def check_inv1(self):
        trades_dir = os.path.join(self.root, "trades")
        trade_dates = set()
        for month_dir in Path(trades_dir).glob("20??-??"):
            trade_dates |= _list_dates_in_dir(str(month_dir))

        perf = _load_json(os.path.join(self.root, "strategies", "performance_history.json")) or []
        perf_dates = {e["date"] for e in perf}

        missing = sorted(trade_dates - perf_dates)
        if missing:
            self._fail("INV-1", f"trade dates without perf entry: {missing}")
        else:
            self._pass("INV-1", f"all {len(trade_dates)} trade dates have perf entry")

    # ── INV-2: Trade file → daily report must exist ──

    def check_inv2(self):
        trades_dir = os.path.join(self.root, "trades")
        trade_dates = set()
        for month_dir in Path(trades_dir).glob("20??-??"):
            trade_dates |= _list_dates_in_dir(str(month_dir))

        reports_dir = os.path.join(self.root, "reports", "daily")
        report_dates = _list_dates_in_dir(reports_dir, "*.md")
        # Exclude premarket files
        report_dates = {d for d in report_dates
                        if os.path.exists(os.path.join(reports_dir, f"{d}.md"))}

        missing = sorted(trade_dates - report_dates)
        if missing:
            self._fail("INV-2", f"trade dates without daily report: {missing}")
        else:
            self._pass("INV-2", f"all {len(trade_dates)} trade dates have daily report")

    # ── INV-3: Three-way consistency (perf / trade / report) ──

    def check_inv3(self):
        """Check perf/trade/report consistency.

        Note: Pre-2026-05 reports were generated by a different agent process
        that used cumulative (not daily) returns. Only enforce consistency
        for dates >= 2026-05-01 where all sources share the same calculation.
        """
        perf = _load_json(os.path.join(self.root, "strategies", "performance_history.json")) or []
        perf_by_date = {e["date"]: e for e in perf}

        mismatches = []
        trades_dir = os.path.join(self.root, "trades")
        for month_dir in sorted(Path(trades_dir).glob("20??-??")):
            for trade_file in sorted(month_dir.glob("*.json")):
                m = re.search(r"(\d{4}-\d{2}-\d{2})", trade_file.name)
                if not m:
                    continue
                date = m.group(1)

                # Skip pre-May dates: old reports use cumulative returns
                if date < "2026-05-01":
                    continue

                trade_data = _load_json(str(trade_file))
                if not trade_data:
                    continue

                snapshots = trade_data.get("account_snapshots", {})
                perf_entry = perf_by_date.get(date)
                if not perf_entry:
                    continue  # covered by INV-1

                # Compare perf vs trade snapshot
                for acct in ["main", "lab"]:
                    trade_pct = snapshots.get(acct, {}).get("daily_pnl_pct")
                    perf_pct = perf_entry.get(f"{acct}_pct")
                    if trade_pct is not None and perf_pct is not None:
                        if abs(trade_pct - perf_pct) > TOLERANCE_PCT:
                            mismatches.append(
                                f"{date} {acct}: perf={perf_pct:+.2f}% trade={trade_pct:+.2f}%"
                            )

                # Compare perf vs daily report
                report_path = os.path.join(self.root, "reports", "daily", f"{date}.md")
                rpt_main, rpt_lab = _extract_report_daily_return(report_path)
                for acct, rpt_pct in [("main", rpt_main), ("lab", rpt_lab)]:
                    perf_pct = perf_entry.get(f"{acct}_pct")
                    if rpt_pct is not None and perf_pct is not None:
                        if abs(rpt_pct - perf_pct) > TOLERANCE_PCT:
                            mismatches.append(
                                f"{date} {acct}: perf={perf_pct:+.2f}% report={rpt_pct:+.2f}%"
                            )

        if mismatches:
            self._fail("INV-3", f"pnl mismatches:\n  " + "\n  ".join(mismatches))
        else:
            self._pass("INV-3", "perf/trade/report all consistent")

    # ── INV-4: HS300 benchmark — no unverified placeholder zeros ──

    def check_inv4(self):
        perf = _load_json(os.path.join(self.root, "strategies", "performance_history.json")) or []
        issues = []
        for e in perf:
            date = e["date"]
            hs = e.get("hs300_pct")
            if hs is None:
                issues.append(f"{date}: hs300_pct is null/missing")
            elif hs == 0:
                # Allow real 0 only if verified
                src = e.get("benchmark_source")
                verified = e.get("benchmark_verified")
                note = e.get("benchmark_note")
                if not (verified or src or note):
                    issues.append(f"{date}: hs300_pct=0 without benchmark_source/verified/note")

        if issues:
            self._fail("INV-4", "unverified benchmark:\n  " + "\n  ".join(issues))
        else:
            self._pass("INV-4", f"all {len(perf)} entries have valid benchmark")

    # ── INV-5: No duplicate dates in performance_history ──

    def check_inv5(self):
        perf = _load_json(os.path.join(self.root, "strategies", "performance_history.json")) or []
        dates = [e["date"] for e in perf]
        dupes = [d for d in dates if dates.count(d) > 1]
        dupes = sorted(set(dupes))
        if dupes:
            self._fail("INV-5", f"duplicate dates: {dupes}")
        else:
            self._pass("INV-5", f"no duplicates in {len(dates)} entries")

    # ── INV-6: Observed ledger coverage (no lost historical dates) ──

    def check_inv6(self):
        # Collect all observed dates across all data sources
        observed = set()

        # trades/
        trades_dir = os.path.join(self.root, "trades")
        for month_dir in Path(trades_dir).glob("20??-??"):
            observed |= _list_dates_in_dir(str(month_dir))

        # reports/daily/ (non-premarket only)
        reports_dir = os.path.join(self.root, "reports", "daily")
        for f in Path(reports_dir).glob("20??-??-??.md"):
            observed.add(f.stem)

        # agents/workflows/ (only settlement-bearing post-market workflows)
        wf_dir = os.path.join(self.root, "agents", "workflows")
        for f in Path(wf_dir).glob("workflow_*.json"):
            if not f.name.startswith("workflow_post_market_"):
                continue
            m = re.search(r"(\d{8})", f.name)
            if m:
                d = m.group(1)
                observed.add(f"{d[:4]}-{d[4:6]}-{d[6:8]}")

        # performance_history
        perf = _load_json(os.path.join(self.root, "strategies", "performance_history.json")) or []
        perf_dates = {e["date"] for e in perf}
        observed |= perf_dates

        if not observed:
            self._skip("INV-6", "no observed dates to check")
            return

        min_date = min(observed)
        max_date = max(observed)

        # Coverage = perf_dates / observed_dates (excluding non-trading gaps)
        missing = sorted(observed - perf_dates)
        coverage = (len(observed) - len(missing)) / len(observed) * 100

        if missing:
            self._fail("INV-6",
                       f"coverage {coverage:.0f}% ({len(perf_dates)}/{len(observed)}), "
                       f"missing from perf: {missing}")
        else:
            self._pass("INV-6", f"coverage 100% ({len(perf_dates)}/{len(observed)} dates)")

    # ── INV-7: Live accounts align with performance ──

    def check_inv7(self):
        accounts_dir = os.path.join(self.root, "accounts")
        if not os.path.exists(accounts_dir):
            self._skip("INV-7", "accounts/ not found (CI or clean clone)")
            return

        main_acc = _load_json(os.path.join(accounts_dir, "main.json"))
        lab_acc = _load_json(os.path.join(accounts_dir, "lab.json"))
        if not main_acc or not lab_acc:
            self._skip("INV-7", "account files not readable")
            return

        # Only check if updated_at is recent (within last trading day)
        main_updated = main_acc.get("updated_at", "")
        if not main_updated:
            self._skip("INV-7", "no updated_at in account")
            return

        # Extract date from updated_at
        m = re.search(r"(\d{4}-\d{2}-\d{2})", main_updated)
        if not m:
            self._skip("INV-7", "cannot parse updated_at date")
            return
        acct_date = m.group(1)

        perf = _load_json(os.path.join(self.root, "strategies", "performance_history.json")) or []
        perf_entry = next((e for e in perf if e["date"] == acct_date), None)
        if not perf_entry:
            self._skip("INV-7", f"no perf entry for account date {acct_date}")
            return

        mismatches = []
        for acct_type, acc_data in [("main", main_acc), ("lab", lab_acc)]:
            acct_pct = acc_data.get("daily_pnl_pct")
            perf_pct = perf_entry.get(f"{acct_type}_pct")
            if acct_pct is not None and perf_pct is not None:
                if abs(acct_pct - perf_pct) > 0.06:  # wider tolerance for live accounts
                    mismatches.append(
                        f"{acct_date} {acct_type}: account={acct_pct:+.2f}% perf={perf_pct:+.2f}%"
                    )

        if mismatches:
            self._fail("INV-7", "account/perf mismatch:\n  " + "\n  ".join(mismatches))
        else:
            self._pass("INV-7", f"accounts aligned for {acct_date}")

    # ── Run all ──

    def validate(self) -> List[dict]:
        self.results = []
        self.check_inv1()
        self.check_inv2()
        self.check_inv3()
        self.check_inv4()
        self.check_inv5()
        self.check_inv6()
        if self.strict:
            self.check_inv7()
        return self.results

    def summary(self) -> str:
        lines = []
        fails = 0
        for r in self.results:
            tag = r["status"]
            lines.append(f"[{tag}] {r['inv']}: {r['msg']}")
            if tag == "FAIL":
                fails += 1
        lines.append(f"\nResult: {len(self.results) - fails}/{len(self.results)} PASS")
        if fails:
            lines.append(f"FAILED: {fails} invariant(s) violated")
        return "\n".join(lines)


def main():
    strict = "--strict" in sys.argv
    v = LedgerValidator(strict=strict)
    v.validate()
    print(v.summary())
    fails = sum(1 for r in v.results if r["status"] == "FAIL")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
